package com.akasha.app;

import java.util.ArrayList;
import java.util.List;

/**
 * One entry in the experience pool. Written by an agent (type=agent),
 * auto-generated by the system (type=auto), or published by the user (type=user).
 * Media (images/videos) are stored as files under files/exps/media/ and referenced by name.
 *
 * Enhanced v3: adds usage tracking, importance scoring, LRU retention support,
 * and source tracing for automatic experience writing.
 */
public class Experience {
    public String id;
    public String agentId;
    public String agentName;
    public String title;
    public String content;
    public String type = "agent"; // 'agent' | 'user' | 'auto'
    public long time = 0;
    public List<String> media = new ArrayList<>();

    // === Enhanced v3 fields ===
    public long lastUsedTime = 0;     // last retrieval/use time (LRU key)
    public int useCount = 0;          // total retrieval count
    public double importance = 0.5;   // importance score 0-1
    public String sourceSessionId = ""; // source session for traceability
    public String tags = "";          // comma-separated tags for retrieval
    public boolean userEdited = false; // user has manually edited this entry

    /** Computed score for LRU retention: importance * decay + usage bonus. */
    public double retentionScore() {
        long now = System.currentTimeMillis();
        double ageDays = Math.max(0, (now - (lastUsedTime > 0 ? lastUsedTime : time)) / 86400000.0);
        double decay = Math.exp(-ageDays / 30.0); // 30-day half-life
        return importance * decay + 0.1 * useCount;
    }

    /** Returns true if this experience should be protected from auto-deletion. */
    public boolean isProtected() {
        return userEdited || importance >= 0.9;
    }
}
